export const locations = {
  Ariana: {
    delegations: [
      'Ariana Ville',
      'Borj El Baccouch',
      'Borj Louzir',
      'Borj Touil',
      'Cebelet Ben Ammar',
      'Chargia II',
      'Cite El Ghazela',
      'Ennasr 1',
      'Ennasr 2',
      'Kalaat Landlous',
      'La Soukra',
      'Menzah 1',
      'Menzah 2',
      'Menzah 6',
      'Menzah 7',
      'Menzah 8',
      'Mnihla',
      'Raouad',
      'Riadh El Andalous',
    ],
  },
  Ben_Arous: {
    delegations: [
      'Ben Arous',
      'Bir EL Bey',
      'Bir EL Kassaa',
      'Borj Cedria',
      'Boukornine',
    ],
  },
  Bizerte: {},
  Beja: {},
  Gabes: {},
  Gafsa: {},
  Jendouba: {},
  Kairouan: {},
  Kasserine: {},
  Kebili: {},
  La_Manouba: {},
  Le_Kef: {},
  Mahdia: {},
  Monastir: {},
  Medenine: {},
  Nabeul: {},
  Sfax: {},
  Sidi_Bouzid: {},
  Siliana: {},
  Sousse: {},
  Tataouine: {},
  Tozeur: {},
  Tunis: {},
  Zaghouan: {},
};
